Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ChallengeSnow.Models
{
    public class Order
    {
        public Guid Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMMM dd yyyy}")]
        [Display(Name = "Created")]
        public DateTime Date_Created { get; set; }
        public ItemBase Item_Number { get; set; }
        
        [Display(Name = "Item")]
        public Guid Item_NumberId { get; set; }

        public int Quantity { get; set; }
    }
}

Controllers/OrdersController.cs
using ChallengeSnow.Interfaces;
using ChallengeSnow.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChallengeSnow.Controllers
{
    public class OrdersController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var result = await OrderManager.GetOrders();
            return HandleResult(result);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Get(Guid id)
        {
            return HandleResult(await OrderManager.GetOrders(id));
        }


        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            return HandleResult(await OrderManager.RemoveOrder(id));
        }


        [HttpPost]
        public async Task<ActionResult> Create(Order order)
        {
            return HandleResult(await OrderManager.AddOrder(order));
        }

        [HttpPut]
        public async Task<IActionResult> Update(Order order)
        {
            return HandleResult(await OrderManager.UpdateOrder(order));
        }
    }
}

Pages/Deal_Items/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChallengeSnow.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChallengeSnow.Pages.Deal_Items
{
    public class CreateModel : BaseRazorPage
    {
        [BindProperty]
        public Deal_Item Deal { get; set; }

        public void OnGet()
        {
        }

        public async Task<ActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var result = await OrderManager.AddDeal(Deal);
                return HandleResult(result);
            }
            else
            {
                return Page();
            }
        }

    }
}

Pages/Items/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChallengeSnow.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChallengeSnow.Pages.Items
{
    public class CreateModel : BaseRazorPage
    {
        [BindProperty] // to bind on post to this bookd
        public Item Item { get; set; }

        public void OnGet()
        {
        }

        public async Task<ActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
               var result = await OrderManager.AddItem(Item);
                return HandleResult(result);
            }
            else
            {
                return Page();
            }
        }

    }
}

Pages/Items/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChallengeSnow.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChallengeSnow.Pages.Items
{
    public class IndexModel : BaseRazorPage
    {
        public IEnumerable<Item> Items { get; set; }
        

        public async void OnGet()
        {
            var items = await OrderManager.GetItems();
            
            Items = items.Value;
        }

        public async Task<IActionResult> OnPostDelete(Guid id)
        {
            var result = await OrderManager.RemoveItem(id);
            return HandleResult(result);    
        }
    }
}

Pages/Orders/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChallengeSnow.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ChallengeSnow.Pages.Orders
{
    public class CreateModel : BaseRazorPage
    {
        [BindProperty]
        public Order Order { get; set; }

        [BindProperty]
        public List<SelectListItem> Options { get; set; }


        public async Task<IActionResult> OnGet(Guid Id)
        {
            StartOptions();

            Order = new Order();
            if (Id == Guid.Empty) return Page();

            var result = await OrderManager.GetOrders(Id);
            if (result.IsSuccess) Order = result.Value;
            return HandleResult(result);
        }

        public async void StartOptions()
        {
            var items = await OrderManager.GetAllItems();
            Options = items.Value.Select(a =>
                                new SelectListItem
                                {
                                    Value = a.Id.ToString(),
                                    Text = a.Description
                                }).ToList();

            Options.Insert(0, new SelectListItem
            {
                Value = Guid.Empty.ToString(),
                Text = "Select"
            });
        }

        public async Task<ActionResult> OnPost()
        {
            if (ModelState.IsValid && Order.Item_NumberId != Guid.Empty)
            {
                var result = await OrderManager.AddOrder(Order);

                if (result == null) return NotFound();
                if (result.IsSuccess && result.Value != null)
                    return RedirectToPage("Index");
                if (result.IsSuccess && !result.Value == null)
                    return NotFound();

                ViewData["Message"] = result.Error;
            }

            StartOptions();
            return Page();
        }
    }
}

Pages/Orders/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChallengeSnow.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChallengeSnow.Pages.Orders
{
    public class DetailModel : BaseRazorPage
    {
        [BindProperty]
        public Order Order { get; set; }
        public decimal Profit { get; set; }
        public decimal Reduced_price { get; set; } = 0;


        public async Task<IActionResult> OnGet(Guid id)
        {
            var result = await OrderManager.GetOrders(id);

            if (!result.IsSuccess) return NotFound();

            Order = result.Value;

            var dealitem = Order.Item_Number as Deal_Item;
            if (dealitem != null)
            {
                Profit = Calculating.GetProfit(Order, dealitem); // Is it a deal item?
                Reduced_price = dealitem.Reduced_price;
            }
            else Profit = Calculating.GetProfit(Order, (Item)Order.Item_Number);

            return Page();
        }
    }
}

Pages/Orders/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChallengeSnow.Interfaces;
using ChallengeSnow.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChallengeSnow.Pages.Orders
{
    public class IndexModel : BaseRazorPage
    {
        public IEnumerable<Order> Orders { get; set; }


        public async void OnGet()
        {
            var orders = await OrderManager.GetOrders();
            Orders = orders.Value;
        }
    }
}

Pages/Orders/Create.cshtml
@page
@model ChallengeSnow.Pages.Orders.CreateModel
@{
}
<br />
<h2 class="text-info">Create New Order</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly">

        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Order.Quantity"></label>
            </div>
            <div class="col-6">
                <input asp-for="Order.Quantity" class="form-control" />
            </div>
            <span asp-validation-for="Order.Quantity" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Order.Item_NumberId"></label>
            </div>
            <div class="col-6">
                <select asp-items="Model.Options" asp-for="Order.Item_NumberId" class="form-control"></select>
            </div>
            <span asp-validation-for="Order.Item_NumberId" class="text-danger"></span>
        </div>
       <div class="form-group row">
            <div class="col-3 offset-4">
                <input type="submit" value="Create" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
    @if (ViewData["Message"] != null)
    {
        <script type="text/javascript">
                    window.onload = function () {
                        alert("@ViewData["Message"]");
                    };
        </script>
    }
</div>



@*to make the validation not enter the client side*@
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Pages/Orders/Detail.cshtml
@page
@model ChallengeSnow.Pages.Orders.DetailModel
@{
}
<br />
<h3 class="text-info">Order No. @(Model.Order.Id) </h3>
<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly">

        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Order.Quantity"></label>
            </div>
            <div class="col-5">
                @Html.DisplayFor(x => x.Order.Quantity)
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Order.Item_NumberId"></label>
            </div>
            <div class="col-5">
                @Html.DisplayFor(x => x.Order.Item_Number.Description)
                
                
            </div>
        
    </div>
    <div class="form-group row">
            <div class="col-4">
                <label asp-for="Order.Item_Number.Price"></label>
            </div>
            <div class="col-5">
                
                @if (Model.Reduced_price > 0)
                {
                    @Html.DisplayFor(x => x.Reduced_price)
                }
                else
                {
                    @Html.DisplayFor(x => x.Order.Item_Number.Price)
                }
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Order.Date_Created"></label>
            </div>
            <div class="col-5">
                @Html.DisplayFor(x => x.Order.Date_Created)
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Profit"></label>
            </div>
            <div class="col-5">
                $@Html.DisplayFor(x => x.Profit)
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4 offset-4">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
    @if (ViewData["Message"] != null)
    {
        <script type="text/javascript">
                    window.onload = function () {
                        alert("@ViewData["Message"]");
                    };
        </script>
    }
</div>

Pages/Orders/Index.cshtml
@page
@model ChallengeSnow.Pages.Orders.IndexModel
@{
}

<br />
<div class="container row p=0 m=0">
    <div class="col-9">
        <h2 class="text-info"> Order List</h2>
    </div>
    <div class="col-3">
        <a asp-page="Create" class="btn btn-info form-control text-white">Create New Order</a>
    </div>

    <div class="col-12 border p-3 mt-3">
        <form method="post">
            @if (Model.Orders.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="Orders.FirstOrDefault().Id"></label>
                        </th>
                        <th>
                            <label asp-for="Orders.FirstOrDefault().Date_Created"></label>
                        </th>
                        <th>
                            <label asp-for="Orders.FirstOrDefault().Item_Number"></label>
                        </th>
                        <th>
                            <label asp-for="Orders.FirstOrDefault().Quantity"></label>
                        </th>
                        <th>

                        </th>

                    </tr>
                    @foreach (var item in Model.Orders)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Date_Created)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Item_Number.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Quantity)
                            </td>
                            <td>
                                <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger btn-sm text-white">Delete</button>
                                <a asp-page="Detail" asp-route-Id="@item.Id" class="btn btn-success btn-sm text-white">Profit</a>
                            </td>
                        </tr>

                    }

                </table>
            }
            else
            {
                <p>No Orders available </p>
            }
        </form>
        @if (ViewData["Message"] != null)
            {
                <script type="text/javascript">
                    window.onload = function () {
                        alert("@ViewData["Message"]");
                    };
                </script>
            }
        
    </div>



</div>